/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// ErrataRequest struct for ErrataRequest
type ErrataRequest struct {
	Page float32 `json:"page,omitempty"`
	PageSize float32 `json:"page_size,omitempty"`
	ErrataList []string `json:"errata_list"`
	ModifiedSince string `json:"modified_since,omitempty"`
}
