/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// UpdatesRequestModulesList struct for UpdatesRequestModulesList
type UpdatesRequestModulesList struct {
	ModuleName string `json:"module_name"`
	ModuleStream string `json:"module_stream"`
}
