/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// UpdatesResponseModulesList struct for UpdatesResponseModulesList
type UpdatesResponseModulesList struct {
	ModuleName string `json:"module_name,omitempty"`
	ModuleStream string `json:"module_stream,omitempty"`
}
