/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// DbChangeResponse struct for DbChangeResponse
type DbChangeResponse struct {
	Dbchange DbChangeResponseDbchange `json:"dbchange,omitempty"`
}
