/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// PackagesResponseRepositories struct for PackagesResponseRepositories
type PackagesResponseRepositories struct {
	Label string `json:"label,omitempty"`
	Name string `json:"name,omitempty"`
	Basearch string `json:"basearch,omitempty"`
	Releasever string `json:"releasever,omitempty"`
}
