/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// UpdatesResponseAvailableUpdates struct for UpdatesResponseAvailableUpdates
type UpdatesResponseAvailableUpdates struct {
	Repository string `json:"repository,omitempty"`
	Releasever string `json:"releasever,omitempty"`
	Basearch string `json:"basearch,omitempty"`
	Erratum string `json:"erratum,omitempty"`
	Package string `json:"package,omitempty"`
}
