/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// PackagesResponse struct for PackagesResponse
type PackagesResponse struct {
	PackageList map[string]PackagesResponsePackageList `json:"package_list,omitempty"`
}
