/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// VulnerabilitiesResponse struct for VulnerabilitiesResponse
type VulnerabilitiesResponse struct {
	CveList []string `json:"cve_list,omitempty"`
}
