/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// ReposRequest struct for ReposRequest
type ReposRequest struct {
	Page float32 `json:"page,omitempty"`
	PageSize float32 `json:"page_size,omitempty"`
	RepositoryList []string `json:"repository_list"`
	// Return only repositories changed after the given date
	ModifiedSince string `json:"modified_since,omitempty"`
}
