/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// UpdatesV2ResponseUpdateList struct for UpdatesV2ResponseUpdateList
type UpdatesV2ResponseUpdateList struct {
	AvailableUpdates []UpdatesResponseAvailableUpdates `json:"available_updates,omitempty"`
}
