/*
 * VMaaS Webapp
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package vmaas
// PackagesRequest struct for PackagesRequest
type PackagesRequest struct {
	PackageList []string `json:"package_list"`
}
