/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// FactSet A set of string facts belonging to a single namespace.
type FactSet struct {
	// The facts themselves.
	Facts map[string]interface{} `json:"facts"`
	// A namespace the facts belong to.
	Namespace string `json:"namespace"`
}
