/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// YumRepo Representation of one yum repository
type YumRepo struct {
	Baseurl string `json:"baseurl,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	Gpgcheck bool `json:"gpgcheck,omitempty"`
	Name string `json:"name,omitempty"`
}
