/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// PatchHostIn Data of a single host to be updated.
type PatchHostIn struct {
	// The ansible host name for remediations
	AnsibleHost string `json:"ansible_host,omitempty"`
	// A host’s human-readable display name, e.g. in a form of a domain name.
	DisplayName string `json:"display_name,omitempty"`
}
