/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// StructuredTag struct for StructuredTag
type StructuredTag struct {
	Key string `json:"key,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Value *string `json:"value,omitempty"`
}
