/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// BulkHostOutDetails struct for BulkHostOutDetails
type BulkHostOutDetails struct {
	// Details about why a host failed to be created or updated.
	Detail string `json:"detail,omitempty"`
	Host CreateHostOut `json:"host,omitempty"`
	// HTTP status code of the results of the host create/update process
	Status int32 `json:"status,omitempty"`
	// Short description of why a host failed to be created or updated.
	Title string `json:"title,omitempty"`
}
