/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// DiskDevice Representation of one mounted device
type DiskDevice struct {
	Device string `json:"device,omitempty"`
	// user-defined mount label
	Label string `json:"label,omitempty"`
	// mount point
	MountPoint string `json:"mount_point,omitempty"`
	Options DiskDeviceOptions `json:"options,omitempty"`
	// mount type
	Type string `json:"type,omitempty"`
}
