/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// DiskDeviceOptions mount options
type DiskDeviceOptions struct {
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
