/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// NetworkInterface Representation of one network interface
type NetworkInterface struct {
	Ipv4Addresses []string `json:"ipv4_addresses,omitempty"`
	Ipv6Addresses []string `json:"ipv6_addresses,omitempty"`
	// MAC address (with or without colons)
	MacAddress string `json:"mac_address,omitempty"`
	// MTU
	Mtu int32 `json:"mtu,omitempty"`
	// name of interface
	Name string `json:"name,omitempty"`
	// interface state (UP, DOWN, UNKNOWN)
	State string `json:"state,omitempty"`
	// interface type (ether, loopback)
	Type string `json:"type,omitempty"`
}
