/*
 * Insights Host Inventory REST Interface
 *
 * REST interface for the Insights Platform Host Inventory application.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventory
// SystemProfileByHostOut Structure of the output of the host system profile query
type SystemProfileByHostOut struct {
	// A number of entries on the current page.
	Count int32 `json:"count"`
	// A current page number.
	Page int32 `json:"page"`
	// A page size – a number of entries per single page.
	PerPage int32 `json:"per_page"`
	// Actual host search query result entries.
	Results []HostSystemProfileOut `json:"results"`
	// A total count of the found entries.
	Total int32 `json:"total"`
}
